ALTER TABLE "click_events" ALTER COLUMN "id" SET DATA TYPE bigint USING id::bigint;--> statement-breakpoint
ALTER TABLE "click_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "click_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1);--> statement-breakpoint
ALTER TABLE "click_events" ALTER COLUMN "block_id" SET DATA TYPE uuid USING block_id::uuid;--> statement-breakpoint
ALTER TABLE "click_events" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone;--> statement-breakpoint
ALTER TABLE "click_events" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "click_events" DROP COLUMN "referrer";--> statement-breakpoint
ALTER TABLE "click_events" ADD CONSTRAINT "click_events_block_id_blocks_id_fk" FOREIGN KEY ("block_id") REFERENCES "public"."blocks"("id") ON DELETE cascade ON UPDATE no action;